baseURL: /
disablePathToLower: true
languageCode: en-us
title: Nathan's Blog
theme: "offset"

params:
  author: Nathan Maynes
  subtitle: infrequent posts about things I am working on
  dateFmt: '02.01.2006 15:04'
  mainSections:
    - post
menu:
  main:
    - identifier: posts
      name: Posts
      url: /post/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: design
      name: Design
      url: /design/
      weight: 5
    - identifier: ai-use-disclosure
      name: AI Use Disclosure
      url: /ai-use-disclosure/
      weight: 6
  footer:
    - name: Github
      url: 'https://github.com/nmaynes'
      weight: 1
    - name: X
      url: 'https://x.com/nathanmaynes'
      weight: 2
outputs:
  section:
      - html
ignoreLogs:
  warning-goldmark-raw-html

markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: false
    lineNumbersInTable: false
    tabWidth: 4
