baseURL: /
disablePathToLower: true
languageCode: en-us
title: Nathan's Blog
theme: "smol"

params:
  subtitle: infrequent posts about things I am working on
  dateFmt: '02.01.2006 15:04'
  calendarURL: webcal://www.fcps.edu/events/15/calendar.ics
menu:
  main:
    - identifier: family-culture
      name: Family Culture
      url: /family-culture/
      weight: 1
    - identifier: posts
      name: Posts
      url: /post/
      weight: 2
    - identifier: events
      name: Events
      url: /event/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 5
  footer:
    - name: Github
      url: 'https://github.com/nmaynes'
      weight: 1
    - name: Twitter
      url: 'https://twitter.com/nathanmaynes'
      weight: 2
outputs:
  section:
      - html
ignoreLogs:
  warning-goldmark-raw-html
